from datetime import timedelta
from os import path, getenv
# from dotenv import load_dotenv


# basedir = path.abspath(path.dirname(__file__))
# load_dotenv(path.join(basedir, '../.env'))

URL_PREFIX = '/api/v1'

MONGO_URI_USERS = getenv('MONGO_URI_USERS')
MONGO_URI_COURSES = getenv('MONGO_URI_COURSES')
MONGO_URI_QUESTIONS = getenv('MONGO_URI_QUESTIONS')
MONGO_URI_BENEFITS_CLUB = getenv('MONGO_URI_BENEFITS_CLUB')
#MONGO_URI_MODULES = getenv('MONGO_URI_MODULES')

REDIS_HOST = getenv('REDIS_HOST')
REDIS_PORT = getenv('REDIS_PORT')

RABBITMQ_USER = getenv('RABBITMQ_USER')
RABBITMQ_PASS = getenv('RABBITMQ_PASS')
RABBITMQ_HOST = getenv('RABBITMQ_HOST')
RABBITMQ_PORT = getenv('RABBITMQ_PORT')

JWT_TOKEN_LOCATION = [getenv('JWT_TOKEN_LOCATION')]
JWT_COOKIE_SECURE = eval(getenv('JWT_COOKIE_SECURE'))
JWT_SECRET_KEY = getenv('JWT_SECRET_KEY')
JWT_ACCESS_TOKEN_EXPIRES = timedelta(hours = int(getenv('JWT_ACCESS_TOKEN_EXPIRES')))
JWT_REFRESH_EXPIRES = timedelta(hours = int(getenv('JWT_REFRESH_EXPIRES')))

AWS_DEFAULT_REGION = getenv('AWS_DEFAULT_REGION')
AWS_ACCESS_KEY_ID = getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = getenv('AWS_SECRET_ACCESS_KEY')
AWS_URL = getenv('AWS_URL')

CERTIFICATE_BACKGROUND_IMAGE_URL = getenv('CERTIFICATE_BACKGROUND_IMAGE_URL')
CERTIFICATE_FONT_PERSON_NAME_URL = getenv('CERTIFICATE_FONT_PERSON_NAME_URL')
CERTIFICATE_FONT_COURSE_NAME_URL = getenv('CERTIFICATE_FONT_COURSE_NAME_URL')
CERTIFICATE_FONT_COURSE_HOURS_URL =  getenv('CERTIFICATE_FONT_COURSE_HOURS_URL')
CERTIFICATE_FONT_COMPLETION_DATE_URL = getenv('CERTIFICATE_FONT_COMPLETION_DATE_URL')
