from os import getenv

QUEUE_NAME = 'queue_email'
RABBITMQ_USER = getenv('RABBITMQ_USER')
RABBITMQ_PASS = getenv('RABBITMQ_PASS')
RABBITMQ_HOST = getenv('RABBITMQ_HOST')
RABBITMQ_PORT = getenv('RABBITMQ_PORT')

MAIL_HOST = getenv('MAIL_HOST')
MAIL_PORT = getenv('MAIL_PORT')
MAIL_USERNAME = getenv('MAIL_USERNAME')
MAIL_PASSWORD = getenv('MAIL_PASSWORD')
MAIL_DEFAULT_SENDER = getenv('MAIL_DEFAULT_SENDER')
